"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import environ

AUTH_USER_MODEL = "core.CustomUser"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DJANGO_DEBUG=(bool, False),
)

# ✅ .env 로드: backend/config/.env 우선, 없으면 backend/.env
_env_path_candidates = [
    os.path.join(BASE_DIR, "config", ".env"),
    os.path.join(BASE_DIR, ".env"),
]
for _p in _env_path_candidates:
    if os.path.exists(_p):
        environ.Env.read_env(_p)
        break

# ✅ .env 값 사용(없으면 기본값)
SECRET_KEY = env("SECRET_KEY", default="dev-secret-key")
DEBUG = env("DJANGO_DEBUG", default=False)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# ✅ 아래 하드코딩된 SECRET_KEY/DEBUG는 .env 값을 덮어쓰므로 제거

# 개발 기본 호스트 허용(운영은 .env에서 지정)
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["127.0.0.1", "localhost"])

# Application definition

INSTALLED_APPS = [
    "daphne",
    "channels",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core",
    "approval",
    "board",
    "meeting",
    "resources",
    "operation",
    "chat",
    "timeline",
    "contact",
    "rest_framework",
    "corsheaders",
    "rest_framework_simplejwt.token_blacklist",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"

# Channels (개발용: InMemory. 운영은 Redis로 전환 권장)
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    }
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env("DB_NAME"),
        'USER': env("DB_USER"),
        'PASSWORD': env("DB_PASSWORD"),
        'HOST': env("DB_HOST"),
        # DB_PORT가 있으면 우선 사용, 없으면 LOCAL_PORT(SSH 터널용 등) fallback
        'PORT': env("DB_PORT", default=env("LOCAL_PORT", default="5432")),
        'CONN_MAX_AGE': 5,
        "OPTIONS": {
            "options": "-c lc_messages=C -c client_encoding=UTF8",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# Media (개발용: 로컬 저장소, NAS는 운영에서 전환)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# (선택) 업로드 용량 제한(필요 시)
# DATA_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024  # 20MB

# -----------------------------
# DRF / JWT (SimpleJWT)
# -----------------------------
REST_FRAMEWORK = {
    # API는 기본적으로 JWT로 보호
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        # admin(세션 로그인)도 같이 쓰고 싶으면 아래 줄 유지
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}

# (선택) 토큰 유효기간 기본값 그대로 써도 되지만,
# 나중에 운영 정책에 맞게 조절할 수 있도록 블록만 만들어둠
from datetime import timedelta
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "BLACKLIST_AFTER_ROTATION": True,
}

# -----------------------------
# CORS (프론트 개발 서버 허용)
# -----------------------------
# .env에서 콤마로 구분해서 넣으면 됨:
# CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
CORS_ALLOWED_ORIGINS = env.list(
    "CORS_ALLOWED_ORIGINS",
    default=["http://localhost:3000", "http://127.0.0.1:3000"],
)

# (선택) 프론트에서 Authorization 헤더를 확실히 쓰기 위해
CORS_ALLOW_HEADERS = list(default_headers := (
    "accept", "accept-encoding", "authorization", "content-type",
    "dnt", "origin", "user-agent", "x-csrftoken", "x-requested-with",
))