"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import environ
import dj_database_url

AUTH_USER_MODEL = "core.CustomUser"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DJANGO_DEBUG=(bool, False),
)

# Load .env from backend/config/.env first, then backend/.env.
_env_path_candidates = [
    os.path.join(BASE_DIR, "config", ".env"),
    os.path.join(BASE_DIR, ".env"),
]
for _p in _env_path_candidates:
    if os.path.exists(_p):
        environ.Env.read_env(_p)
        break

# Use .env values when available (with safe defaults).
SECRET_KEY = env("SECRET_KEY", default="dev-secret-key")
DEBUG = env("DJANGO_DEBUG", default=False)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# Removed hardcoded SECRET_KEY/DEBUG override to keep .env authoritative.

# Default local hosts; configure production hosts via .env.
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["127.0.0.1", "localhost"])

# Application definition

INSTALLED_APPS = [
    "daphne",
    "channels",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core",
    "approval",
    "board",
    "meeting",
    "resources",
    "project",

    "chat",
    "timeline",
    "contact",
    "operation",
    "django_filters",
    "rest_framework",
    "corsheaders",
    "rest_framework_simplejwt.token_blacklist",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"

# Channels: InMemory layer for single-instance setup.
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    }
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DATABASE_URL = env("DATABASE_URL", default="")
DB_CONNECT_TIMEOUT = env.int("DB_CONNECT_TIMEOUT", default=10)
DB_SSLMODE = env("DB_SSLMODE", default="")
DB_SSLROOTCERT = env("DB_SSLROOTCERT", default="")
DB_SSLCERT = env("DB_SSLCERT", default="")
DB_SSLKEY = env("DB_SSLKEY", default="")
DB_PG_OPTIONS = env("DB_PG_OPTIONS", default="")


def _database_options():
    options = {
        "connect_timeout": DB_CONNECT_TIMEOUT,
    }
    if DB_PG_OPTIONS:
        options["options"] = DB_PG_OPTIONS
    if DB_SSLMODE:
        options["sslmode"] = DB_SSLMODE
    if DB_SSLROOTCERT:
        options["sslrootcert"] = DB_SSLROOTCERT
    if DB_SSLCERT:
        options["sslcert"] = DB_SSLCERT
    if DB_SSLKEY:
        options["sslkey"] = DB_SSLKEY
    return options

if DATABASE_URL:
    _db = dj_database_url.parse(DATABASE_URL, conn_max_age=5)
    _db_options = _db.get("OPTIONS", {})
    _db_options.update(_database_options())
    _db["OPTIONS"] = _db_options
    DATABASES = {
        "default": _db,
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': env("DB_NAME"),
            'USER': env("DB_USER"),
            'PASSWORD': env("DB_PASSWORD"),
            'HOST': env("DB_HOST"),
            # DB_PORT preferred; fallback to LOCAL_PORT for SSH tunnel setups.
            'PORT': env("DB_PORT", default=env("LOCAL_PORT", default="5432")),
            'CONN_MAX_AGE': 5,
            "OPTIONS": _database_options(),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Media: local path by default. Move to external storage in production if needed.
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Optional upload size limit (enable if needed).
# DATA_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024  # 20MB

# -----------------------------
# Email (SMTP) Settings
# -----------------------------
EMAIL_BACKEND = env("EMAIL_BACKEND", default="django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = env("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = env.int("EMAIL_PORT", default=587)
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="noreply@p6ix.com")

# -----------------------------
# DRF / JWT (SimpleJWT)
# -----------------------------
REST_FRAMEWORK = {
    # Protect API with JWT by default.
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        # Keep SessionAuthentication if Django admin/session login is also used.
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}

# JWT lifetime defaults; tune later for your production policy.
# Kept explicit block to make token policy changes straightforward.
from datetime import timedelta
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "BLACKLIST_AFTER_ROTATION": True,
}

# -----------------------------
# CORS
# -----------------------------
# Set comma-separated origins in .env.
# CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
CORS_ALLOWED_ORIGINS = env.list(
    "CORS_ALLOWED_ORIGINS",
    default=["http://localhost:3000", "http://127.0.0.1:3000"],
)
CORS_ALLOW_CREDENTIALS = env.bool("CORS_ALLOW_CREDENTIALS", default=True)
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

# Optional explicit CORS headers for Authorization support.
CORS_ALLOW_HEADERS = list(default_headers := (
    "accept", "accept-encoding", "authorization", "content-type",
    "dnt", "origin", "user-agent", "x-csrftoken", "x-requested-with",
))
