# Generated by Django 6.0.1 on 2026-01-12 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_group",
                    models.BooleanField(default=False, verbose_name="그룹 채팅"),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="대화방 이름"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="conversations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="참여자",
                    ),
                ),
            ],
            options={
                "verbose_name": "대화방",
                "verbose_name_plural": "대화방",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="HelpQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "답변대기"), ("answered", "답변완료")],
                        default="pending",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("answer", models.TextField(blank=True, verbose_name="답변")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "answered_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="답변일"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="help_questions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "도움말 질문",
                "verbose_name_plural": "도움말 질문",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="메시지 내용")),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="읽음 여부"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.conversation",
                        verbose_name="대화방",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="발신자",
                    ),
                ),
            ],
            options={
                "verbose_name": "메시지",
                "verbose_name_plural": "메시지",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("system", "시스템"),
                            ("notice", "공지사항"),
                            ("approval", "결재"),
                            ("schedule", "일정"),
                            ("message", "메시지"),
                        ],
                        max_length=20,
                        verbose_name="알림 유형",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("message", models.TextField(verbose_name="내용")),
                (
                    "link",
                    models.CharField(blank=True, max_length=500, verbose_name="링크"),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="읽음 여부"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "알림",
                "verbose_name_plural": "알림",
                "ordering": ["-created_at"],
            },
        ),
    ]
