# Generated by Codex on 2026-02-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_department_order"),
        ("chat", "0002_conversation_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to="core.company",
                verbose_name="회사",
            ),
        ),
    ]
