# Generated by Codex on 2026-02-25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_conversation_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="project",
        ),
    ]
