# Generated by Django 6.0.1 on 2026-01-12 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="회사명")),
                (
                    "representative",
                    models.CharField(blank=True, max_length=100, verbose_name="대표자"),
                ),
                (
                    "business_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="사업자번호"
                    ),
                ),
                (
                    "industry",
                    models.CharField(blank=True, max_length=100, verbose_name="업종"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="전화번호"
                    ),
                ),
                (
                    "fax",
                    models.CharField(blank=True, max_length=20, verbose_name="팩스"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="이메일"
                    ),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=300, verbose_name="주소"),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="담당자명"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="담당자 연락처"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="담당자 이메일"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="메모")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_clients",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="등록자",
                    ),
                ),
            ],
            options={
                "verbose_name": "거래처",
                "verbose_name_plural": "거래처",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Estimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estimate_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="견적번호"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="견적 제목")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "작성중"),
                            ("sent", "발송"),
                            ("accepted", "수락"),
                            ("rejected", "거절"),
                            ("expired", "만료"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="공급가액",
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=15, verbose_name="세액"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=15, verbose_name="합계"
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(blank=True, null=True, verbose_name="유효기간"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_estimates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "견적",
                "verbose_name_plural": "견적",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EstimateItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200, verbose_name="품목")),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="수량"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=15, verbose_name="단가"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=15, verbose_name="금액"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="순서")),
                (
                    "estimate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="operation.estimate",
                        verbose_name="견적",
                    ),
                ),
            ],
            options={
                "verbose_name": "견적 항목",
                "verbose_name_plural": "견적 항목",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SalesOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="건명")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("lead", "리드"),
                            ("contact", "접촉"),
                            ("proposal", "제안"),
                            ("negotiation", "협상"),
                            ("won", "수주"),
                            ("lost", "실패"),
                        ],
                        default="lead",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("low", "낮음"), ("medium", "보통"), ("high", "높음")],
                        default="medium",
                        max_length=20,
                        verbose_name="우선순위",
                    ),
                ),
                (
                    "expected_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="예상 금액",
                    ),
                ),
                (
                    "probability",
                    models.PositiveIntegerField(
                        default=50, verbose_name="성공 확률 (%)"
                    ),
                ),
                (
                    "expected_close_date",
                    models.DateField(blank=True, null=True, verbose_name="예상 마감일"),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities",
                        to="operation.client",
                        verbose_name="거래처",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opportunities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="담당자",
                    ),
                ),
            ],
            options={
                "verbose_name": "영업 기회",
                "verbose_name_plural": "영업 기회",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="estimate",
            name="opportunity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="estimates",
                to="operation.salesopportunity",
                verbose_name="영업 기회",
            ),
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="계약번호"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="계약 제목")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "작성중"),
                            ("pending", "검토중"),
                            ("active", "진행중"),
                            ("completed", "완료"),
                            ("terminated", "해지"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="계약 금액",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="시작일"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="종료일"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="operation.client",
                        verbose_name="거래처",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_contracts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contracts",
                        to="operation.salesopportunity",
                        verbose_name="영업 기회",
                    ),
                ),
            ],
            options={
                "verbose_name": "계약",
                "verbose_name_plural": "계약",
                "ordering": ["-created_at"],
            },
        ),
    ]
