# Generated by Django 6.0.1 on 2026-01-14 05:00

import django.db.models.deletion
import django.utils.timezone
import operation.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesPipeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="파이프라인명")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="기본 파이프라인"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "파이프라인",
                "verbose_name_plural": "파이프라인 목록",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="CustomerCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="회사명")),
                (
                    "business_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="사업자번호"
                    ),
                ),
                (
                    "industry",
                    models.CharField(blank=True, max_length=100, verbose_name="업종"),
                ),
                ("address", models.TextField(blank=True, verbose_name="주소")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="대표전화"
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="웹사이트")),
                ("notes", models.TextField(blank=True, verbose_name="메모")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_customer_companies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="등록자",
                    ),
                ),
            ],
            options={
                "verbose_name": "고객사",
                "verbose_name_plural": "고객사 목록",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="이름")),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="직위/직책"
                    ),
                ),
                (
                    "department",
                    models.CharField(blank=True, max_length=100, verbose_name="부서"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="이메일"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="전화번호"
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="휴대전화"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="주 담당자"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="메모")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="operation.customercompany",
                        verbose_name="소속 회사",
                    ),
                ),
            ],
            options={
                "verbose_name": "고객 담당자",
                "verbose_name_plural": "고객 담당자 목록",
                "ordering": ["-is_primary", "name"],
            },
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quote_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="견적번호"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="견적 제목")),
                ("header_text", models.TextField(blank=True, verbose_name="머리말")),
                ("footer_text", models.TextField(blank=True, verbose_name="꼬리말")),
                ("terms", models.TextField(blank=True, verbose_name="거래조건")),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="공급가액",
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=10,
                        max_digits=5,
                        verbose_name="세율(%)",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=15, verbose_name="세액"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=15, verbose_name="총액"
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(blank=True, null=True, verbose_name="견적 유효일"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "작성중"),
                            ("sent", "발송됨"),
                            ("accepted", "수락"),
                            ("rejected", "거절"),
                            ("expired", "만료"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="상태",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="발송일"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="operation.customercompany",
                        verbose_name="고객사",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="operation.customercontact",
                        verbose_name="담당자",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "견적서",
                "verbose_name_plural": "견적서 목록",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuoteItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="순서")),
                ("name", models.CharField(max_length=200, verbose_name="품목명")),
                ("description", models.TextField(blank=True, verbose_name="상세설명")),
                (
                    "specification",
                    models.CharField(blank=True, max_length=100, verbose_name="규격"),
                ),
                (
                    "unit",
                    models.CharField(default="식", max_length=20, verbose_name="단위"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=1, max_digits=10, verbose_name="수량"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=15, verbose_name="단가"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=15, verbose_name="금액"
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=200, verbose_name="비고"),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="operation.quote",
                        verbose_name="견적서",
                    ),
                ),
            ],
            options={
                "verbose_name": "견적 항목",
                "verbose_name_plural": "견적 항목 목록",
                "ordering": ["quote", "order"],
            },
        ),
        migrations.CreateModel(
            name="QuoteTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="템플릿명")),
                ("header_text", models.TextField(blank=True, verbose_name="머리말")),
                ("footer_text", models.TextField(blank=True, verbose_name="꼬리말")),
                ("terms", models.TextField(blank=True, verbose_name="거래조건")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="기본 템플릿"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="등록자",
                    ),
                ),
            ],
            options={
                "verbose_name": "견적 템플릿",
                "verbose_name_plural": "견적 템플릿 목록",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.AddField(
            model_name="quote",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="operation.quotetemplate",
                verbose_name="템플릿",
            ),
        ),
        migrations.CreateModel(
            name="SalesLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="제목(현장/프로젝트명)"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "expected_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=15,
                        null=True,
                        verbose_name="예상금액",
                    ),
                ),
                (
                    "expected_close_date",
                    models.DateField(blank=True, null=True, verbose_name="예상마감일"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "진행중"),
                            ("won", "수주"),
                            ("lost", "실주"),
                        ],
                        default="active",
                        max_length=10,
                        verbose_name="상태",
                    ),
                ),
                (
                    "probability",
                    models.PositiveIntegerField(default=0, verbose_name="확률(%)"),
                ),
                ("lost_reason", models.TextField(blank=True, verbose_name="실주 사유")),
                (
                    "stage_entered_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="단계 진입일"
                    ),
                ),
                (
                    "last_contacted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="최근 접촉일"
                    ),
                ),
                (
                    "next_action_due_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="다음 액션 예정일"
                    ),
                ),
                (
                    "contract_id",
                    models.IntegerField(blank=True, null=True, verbose_name="계약 ID"),
                ),
                (
                    "project_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="프로젝트 ID"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="유입 경로"
                    ),
                ),
                (
                    "tags",
                    models.CharField(blank=True, max_length=500, verbose_name="태그"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "assignees",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assigned_leads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="협업자",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="operation.customercompany",
                        verbose_name="고객사",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="operation.customercontact",
                        verbose_name="담당자",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_leads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="등록자",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_leads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="담당자",
                    ),
                ),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leads",
                        to="operation.salespipeline",
                        verbose_name="파이프라인",
                    ),
                ),
            ],
            options={
                "verbose_name": "영업기회",
                "verbose_name_plural": "영업기회 목록",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="quote",
            name="lead",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotes",
                to="operation.saleslead",
                verbose_name="영업기회",
            ),
        ),
        migrations.CreateModel(
            name="LeadTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "due_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="기한"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("low", "낮음"), ("medium", "보통"), ("high", "높음")],
                        default="medium",
                        max_length=10,
                        verbose_name="우선순위",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="완료"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="완료일"),
                ),
                (
                    "show_on_calendar",
                    models.BooleanField(default=True, verbose_name="캘린더 표시"),
                ),
                (
                    "reminder_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="알림 시간"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lead_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="담당자",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_lead_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="등록자",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="operation.saleslead",
                        verbose_name="영업기회",
                    ),
                ),
            ],
            options={
                "verbose_name": "할 일",
                "verbose_name_plural": "할 일 목록",
                "ordering": ["is_completed", "due_date", "-priority"],
            },
        ),
        migrations.CreateModel(
            name="LeadFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=operation.models.lead_file_path, verbose_name="파일"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="파일명")),
                (
                    "size",
                    models.PositiveIntegerField(default=0, verbose_name="파일 크기"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="업로드일"),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="업로더",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="operation.saleslead",
                        verbose_name="영업기회",
                    ),
                ),
            ],
            options={
                "verbose_name": "첨부파일",
                "verbose_name_plural": "첨부파일 목록",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalesStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="단계명")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="순서")),
                (
                    "stage_type",
                    models.CharField(
                        choices=[("open", "진행중"), ("won", "수주"), ("lost", "실주")],
                        default="open",
                        max_length=10,
                        verbose_name="단계 유형",
                    ),
                ),
                (
                    "probability",
                    models.PositiveIntegerField(default=0, verbose_name="기본 확률(%)"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6", max_length=20, verbose_name="색상"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="operation.salespipeline",
                        verbose_name="파이프라인",
                    ),
                ),
            ],
            options={
                "verbose_name": "영업 단계",
                "verbose_name_plural": "영업 단계 목록",
                "ordering": ["pipeline", "order"],
                "unique_together": {("pipeline", "order")},
            },
        ),
        migrations.AddField(
            model_name="saleslead",
            name="stage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leads",
                to="operation.salesstage",
                verbose_name="현재 단계",
            ),
        ),
        migrations.CreateModel(
            name="LeadActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("note", "메모"),
                            ("call", "전화"),
                            ("email", "이메일"),
                            ("meeting", "미팅"),
                            ("stage_change", "단계변경"),
                            ("quote_sent", "견적발송"),
                            ("file_added", "파일추가"),
                            ("task_done", "TODO완료"),
                            ("won", "수주"),
                            ("lost", "실주"),
                            ("created", "생성"),
                        ],
                        max_length=20,
                        verbose_name="활동 유형",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("content", models.TextField(blank=True, verbose_name="내용")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="operation.saleslead",
                        verbose_name="영업기회",
                    ),
                ),
                (
                    "from_stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="operation.salesstage",
                        verbose_name="이전 단계",
                    ),
                ),
                (
                    "to_stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="operation.salesstage",
                        verbose_name="이후 단계",
                    ),
                ),
            ],
            options={
                "verbose_name": "활동 로그",
                "verbose_name_plural": "활동 로그 목록",
                "ordering": ["-created_at"],
            },
        ),
    ]
