# Generated by Django 6.0.1 on 2026-01-14 00:39

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="회사명")),
                (
                    "representative",
                    models.CharField(blank=True, max_length=100, verbose_name="대표자"),
                ),
                (
                    "business_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="사업자번호"
                    ),
                ),
                (
                    "industry",
                    models.CharField(blank=True, max_length=100, verbose_name="업종"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="전화번호"
                    ),
                ),
                (
                    "fax",
                    models.CharField(blank=True, max_length=20, verbose_name="팩스"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="이메일"
                    ),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=300, verbose_name="주소"),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="담당자명"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="담당자 연락처"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="담당자 이메일"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="메모")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_clients",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="등록자",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="operation.client",
                        verbose_name="상위 거래처",
                    ),
                ),
            ],
            options={
                "verbose_name": "거래처",
                "verbose_name_plural": "거래처",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="계약번호"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="계약 제목")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "작성중"),
                            ("pending", "검토중"),
                            ("active", "진행중"),
                            ("completed", "완료"),
                            ("terminated", "해지"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[("short_term", "단기"), ("long_term", "장기")],
                        default="short_term",
                        max_length=20,
                        verbose_name="계약 유형",
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[
                            ("one_time", "일시불"),
                            ("monthly", "월별"),
                            ("quarterly", "분기별"),
                            ("milestone", "마일스톤"),
                        ],
                        default="one_time",
                        max_length=20,
                        verbose_name="청구 주기",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="계약 금액",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="시작일"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="종료일"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="operation.client",
                        verbose_name="거래처",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_contracts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "계약",
                "verbose_name_plural": "계약",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BillingSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_date", models.DateField(verbose_name="청구 예정일")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=15, verbose_name="청구 예정 금액"
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, verbose_name="설명"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "예정"),
                            ("invoiced", "청구됨"),
                            ("paid", "완납"),
                            ("partial", "부분납"),
                            ("overdue", "연체"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "milestone_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="마일스톤명"
                    ),
                ),
                (
                    "milestone_percentage",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="마일스톤 비율 (%)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_schedules",
                        to="operation.contract",
                        verbose_name="계약",
                    ),
                ),
            ],
            options={
                "verbose_name": "청구 스케줄",
                "verbose_name_plural": "청구 스케줄",
                "ordering": ["scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="Estimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estimate_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="견적번호"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="견적 제목")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "작성중"),
                            ("sent", "발송"),
                            ("accepted", "수락"),
                            ("rejected", "거절"),
                            ("expired", "만료"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="버전"),
                ),
                (
                    "is_final",
                    models.BooleanField(default=False, verbose_name="최종 승인본"),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="공급가액",
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=15, verbose_name="세액"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=15, verbose_name="합계"
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(blank=True, null=True, verbose_name="유효기간"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_estimates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
                (
                    "parent_estimate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revisions",
                        to="operation.estimate",
                        verbose_name="이전 버전",
                    ),
                ),
            ],
            options={
                "verbose_name": "견적",
                "verbose_name_plural": "견적",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EstimateItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200, verbose_name="품목")),
                (
                    "specification",
                    models.CharField(blank=True, max_length=200, verbose_name="규격"),
                ),
                (
                    "unit",
                    models.CharField(default="EA", max_length=20, verbose_name="단위"),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="수량"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=15, verbose_name="단가"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=15, verbose_name="금액"
                    ),
                ),
                (
                    "remark",
                    models.CharField(blank=True, max_length=200, verbose_name="비고"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="순서")),
                (
                    "estimate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="operation.estimate",
                        verbose_name="견적",
                    ),
                ),
            ],
            options={
                "verbose_name": "견적 항목",
                "verbose_name_plural": "견적 항목",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="청구번호"
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="발행일"
                    ),
                ),
                ("due_date", models.DateField(verbose_name="납부 기한")),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="공급가액",
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=15, verbose_name="세액"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=15, verbose_name="합계"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "작성중"),
                            ("sent", "발송"),
                            ("partial", "부분납"),
                            ("paid", "완납"),
                            ("overdue", "연체"),
                            ("cancelled", "취소"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "billing_schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="operation.billingschedule",
                        verbose_name="청구 스케줄",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="operation.contract",
                        verbose_name="계약",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_invoices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "청구서",
                "verbose_name_plural": "청구서",
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_date", models.DateField(verbose_name="입금일")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=15, verbose_name="입금액"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("bank_transfer", "계좌이체"),
                            ("cash", "현금"),
                            ("card", "카드"),
                            ("check", "수표"),
                            ("other", "기타"),
                        ],
                        default="bank_transfer",
                        max_length=20,
                        verbose_name="결제 방법",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="참조번호"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="메모")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="등록자",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="operation.invoice",
                        verbose_name="청구서",
                    ),
                ),
            ],
            options={
                "verbose_name": "수금 기록",
                "verbose_name_plural": "수금 기록",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="QuoteTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="템플릿명")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "column_config",
                    models.JSONField(default=dict, verbose_name="컬럼 설정"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="기본 템플릿"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_quote_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "견적 템플릿",
                "verbose_name_plural": "견적 템플릿",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.AddField(
            model_name="estimate",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="estimates",
                to="operation.quotetemplate",
                verbose_name="템플릿",
            ),
        ),
        migrations.CreateModel(
            name="SalesOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="건명")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("lead", "리드"),
                            ("contact", "접촉"),
                            ("proposal", "제안"),
                            ("negotiation", "협상"),
                            ("won", "수주"),
                            ("lost", "실패"),
                        ],
                        default="lead",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("low", "낮음"), ("medium", "보통"), ("high", "높음")],
                        default="medium",
                        max_length=20,
                        verbose_name="우선순위",
                    ),
                ),
                (
                    "expected_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="예상 금액",
                    ),
                ),
                (
                    "probability",
                    models.PositiveIntegerField(
                        default=50, verbose_name="성공 확률 (%)"
                    ),
                ),
                (
                    "expected_close_date",
                    models.DateField(blank=True, null=True, verbose_name="예상 마감일"),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("next_step", models.TextField(blank=True, verbose_name="다음 단계")),
                (
                    "next_step_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="다음 단계 예정일"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities",
                        to="operation.client",
                        verbose_name="거래처",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opportunities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="담당자",
                    ),
                ),
            ],
            options={
                "verbose_name": "영업 기회",
                "verbose_name_plural": "영업 기회",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="estimate",
            name="opportunity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="estimates",
                to="operation.salesopportunity",
                verbose_name="영업 기회",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="opportunity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contracts",
                to="operation.salesopportunity",
                verbose_name="영업 기회",
            ),
        ),
    ]
