# Generated by Django 6.0.1 on 2026-01-14 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="salesopportunity",
            name="assignees",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_opportunities",
                to=settings.AUTH_USER_MODEL,
                verbose_name="협업자",
            ),
        ),
        migrations.AddField(
            model_name="salesopportunity",
            name="last_contacted_at",
            field=models.DateField(blank=True, null=True, verbose_name="최근 접촉일"),
        ),
        migrations.AddField(
            model_name="salesopportunity",
            name="lost_reason",
            field=models.TextField(blank=True, verbose_name="실주 사유"),
        ),
        migrations.AddField(
            model_name="salesopportunity",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("direct", "직접 영업"),
                    ("referral", "소개"),
                    ("website", "웹사이트"),
                    ("exhibition", "전시회"),
                    ("advertisement", "광고"),
                    ("bidding", "입찰"),
                    ("other", "기타"),
                ],
                default="direct",
                max_length=20,
                verbose_name="유입 경로",
            ),
        ),
        migrations.AddField(
            model_name="salesopportunity",
            name="stage_entered_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="단계 진입 시점"
            ),
        ),
        migrations.CreateModel(
            name="CustomerContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="이름")),
                (
                    "position",
                    models.CharField(blank=True, max_length=50, verbose_name="직책"),
                ),
                (
                    "department",
                    models.CharField(blank=True, max_length=100, verbose_name="부서"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="전화번호"
                    ),
                ),
                (
                    "mobile",
                    models.CharField(blank=True, max_length=20, verbose_name="휴대폰"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="이메일"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="주 담당자"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="메모")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="operation.client",
                        verbose_name="거래처",
                    ),
                ),
            ],
            options={
                "verbose_name": "고객 담당자",
                "verbose_name_plural": "고객 담당자",
                "ordering": ["-is_primary", "name"],
            },
        ),
        migrations.AddField(
            model_name="salesopportunity",
            name="customer_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opportunities",
                to="operation.customercontact",
                verbose_name="고객 담당자",
            ),
        ),
        migrations.CreateModel(
            name="LeadActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("call", "전화"),
                            ("meeting", "미팅"),
                            ("email", "이메일"),
                            ("note", "메모"),
                            ("stage_change", "단계 변경"),
                            ("file_add", "파일 추가"),
                            ("quote_sent", "견적 발송"),
                            ("task_done", "태스크 완료"),
                            ("created", "생성"),
                            ("other", "기타"),
                        ],
                        default="note",
                        max_length=20,
                        verbose_name="활동 유형",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("content", models.TextField(blank=True, verbose_name="내용")),
                (
                    "is_system",
                    models.BooleanField(default=False, verbose_name="시스템 자동 생성"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lead_activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="operation.salesopportunity",
                        verbose_name="영업 기회",
                    ),
                ),
            ],
            options={
                "verbose_name": "영업 활동",
                "verbose_name_plural": "영업 활동",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeadFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="operation/leads/%Y/%m/", verbose_name="파일"
                    ),
                ),
                ("filename", models.CharField(max_length=255, verbose_name="파일명")),
                (
                    "file_size",
                    models.PositiveIntegerField(default=0, verbose_name="파일 크기"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="operation.salesopportunity",
                        verbose_name="영업 기회",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_lead_files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="업로더",
                    ),
                ),
            ],
            options={
                "verbose_name": "영업 첨부파일",
                "verbose_name_plural": "영업 첨부파일",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="LeadTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="기한"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="완료 여부"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="완료 시점"
                    ),
                ),
                (
                    "show_in_calendar",
                    models.BooleanField(default=True, verbose_name="캘린더 표시"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="담당자",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_lead_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="operation.salesopportunity",
                        verbose_name="영업 기회",
                    ),
                ),
            ],
            options={
                "verbose_name": "영업 태스크",
                "verbose_name_plural": "영업 태스크",
                "ordering": ["-is_completed", "due_date"],
            },
        ),
        migrations.CreateModel(
            name="SalesPipeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="파이프라인명")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="기본 파이프라인"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_pipelines",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "영업 파이프라인",
                "verbose_name_plural": "영업 파이프라인",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.AddField(
            model_name="salesopportunity",
            name="pipeline",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opportunities",
                to="operation.salespipeline",
                verbose_name="파이프라인",
            ),
        ),
        migrations.CreateModel(
            name="SalesStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="단계명")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="순서")),
                (
                    "probability",
                    models.PositiveIntegerField(
                        default=0, verbose_name="성공 확률 (%)"
                    ),
                ),
                (
                    "stage_type",
                    models.CharField(
                        choices=[("open", "진행중"), ("won", "수주"), ("lost", "실주")],
                        default="open",
                        max_length=10,
                        verbose_name="단계 유형",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6b7280", max_length=20, verbose_name="색상"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="operation.salespipeline",
                        verbose_name="파이프라인",
                    ),
                ),
            ],
            options={
                "verbose_name": "영업 단계",
                "verbose_name_plural": "영업 단계",
                "ordering": ["pipeline", "order"],
                "unique_together": {("pipeline", "order")},
            },
        ),
        migrations.AddField(
            model_name="salesopportunity",
            name="stage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opportunities",
                to="operation.salesstage",
                verbose_name="단계",
            ),
        ),
    ]
