# Generated by Django 6.0.1 on 2026-01-14 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("operation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customercompany",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operation_customer_companies",
                to="core.company",
                verbose_name="워크스페이스(회사)",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operation_quotes",
                to="core.company",
                verbose_name="워크스페이스(회사)",
            ),
        ),
        migrations.AddField(
            model_name="quotetemplate",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operation_quote_templates",
                to="core.company",
                verbose_name="워크스페이스(회사)",
            ),
        ),
        migrations.AddField(
            model_name="saleslead",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operation_leads",
                to="core.company",
                verbose_name="워크스페이스(회사)",
            ),
        ),
        migrations.AddField(
            model_name="salespipeline",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operation_pipelines",
                to="core.company",
                verbose_name="워크스페이스(회사)",
            ),
        ),
        migrations.AddIndex(
            model_name="customercompany",
            index=models.Index(
                fields=["workspace", "name"], name="operation_c_workspa_da5a21_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="saleslead",
            index=models.Index(
                fields=["workspace", "status", "created_at"],
                name="operation_s_workspa_31e6e7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="saleslead",
            index=models.Index(
                fields=["workspace", "expected_close_date"],
                name="operation_s_workspa_181e00_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="salespipeline",
            index=models.Index(
                fields=["workspace", "name"], name="operation_s_workspa_b5315c_idx"
            ),
        ),
    ]
