# Generated by Django 6.0.1 on 2026-01-15 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("operation", "0002_customercompany_workspace_quote_workspace_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customercompany",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_customer_companies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="담당자",
            ),
        ),
        migrations.AddField(
            model_name="customercompany",
            name="status",
            field=models.CharField(
                choices=[
                    ("prospect", "잠재"),
                    ("active", "진행"),
                    ("deal", "거래"),
                    ("inactive", "중단"),
                ],
                default="prospect",
                max_length=20,
                verbose_name="상태",
            ),
        ),
        migrations.AddField(
            model_name="customercompany",
            name="tags",
            field=models.JSONField(blank=True, default=list, verbose_name="태그"),
        ),
        migrations.AddField(
            model_name="saleslead",
            name="utm",
            field=models.JSONField(blank=True, null=True, verbose_name="UTM"),
        ),
        migrations.AlterField(
            model_name="leadactivity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("note", "메모"),
                    ("call", "전화"),
                    ("email", "이메일"),
                    ("meeting", "미팅"),
                    ("stage_change", "단계변경"),
                    ("quote_created", "견적생성"),
                    ("quote_sent", "견적발송"),
                    ("file_added", "파일추가"),
                    ("task_done", "TODO완료"),
                    ("won", "수주"),
                    ("lost", "실주"),
                    ("created", "생성"),
                ],
                max_length=20,
                verbose_name="활동 유형",
            ),
        ),
        migrations.AlterField(
            model_name="saleslead",
            name="tags",
            field=models.JSONField(blank=True, default=list, verbose_name="태그"),
        ),
        migrations.CreateModel(
            name="EmailSendLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("to", models.CharField(max_length=255, verbose_name="수신자")),
                ("subject", models.CharField(max_length=200, verbose_name="제목")),
                ("body_snapshot", models.TextField(verbose_name="본문 스냅샷")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("sent", "발송"),
                            ("failed", "실패"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="예약발송일"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="발송일"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="오류 메시지"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="등록자",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to="operation.saleslead",
                        verbose_name="영업기회",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operation_email_logs",
                        to="core.company",
                        verbose_name="워크스페이스(회사)",
                    ),
                ),
            ],
            options={
                "verbose_name": "이메일 발송 로그",
                "verbose_name_plural": "이메일 발송 로그 목록",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailSignature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="서명명")),
                ("html", models.TextField(verbose_name="서명 HTML")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="기본 서명"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="등록자",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operation_email_signatures",
                        to="core.company",
                        verbose_name="워크스페이스(회사)",
                    ),
                ),
            ],
            options={
                "verbose_name": "이메일 서명",
                "verbose_name_plural": "이메일 서명 목록",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="템플릿명")),
                ("subject", models.CharField(max_length=200, verbose_name="제목")),
                ("body_html", models.TextField(verbose_name="본문(HTML)")),
                (
                    "variables_schema",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="변수 스키마"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="등록자",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operation_email_templates",
                        to="core.company",
                        verbose_name="워크스페이스(회사)",
                    ),
                ),
            ],
            options={
                "verbose_name": "이메일 템플릿",
                "verbose_name_plural": "이메일 템플릿 목록",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RevenueMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_id",
                    models.IntegerField(blank=True, null=True, verbose_name="계약 ID"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="항목명")),
                (
                    "planned_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=15,
                        null=True,
                        verbose_name="예정금액",
                    ),
                ),
                (
                    "planned_date",
                    models.DateField(blank=True, null=True, verbose_name="예정일"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "계획"),
                            ("invoiced", "청구"),
                            ("collected", "수금완료"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="등록자",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revenue_milestones",
                        to="operation.saleslead",
                        verbose_name="영업기회",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operation_revenue_milestones",
                        to="core.company",
                        verbose_name="워크스페이스(회사)",
                    ),
                ),
            ],
            options={
                "verbose_name": "매출 계획",
                "verbose_name_plural": "매출 계획 목록",
                "ordering": ["-planned_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=15,
                        null=True,
                        verbose_name="금액",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="수금 예정일"),
                ),
                (
                    "received_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="수금일"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "예정"),
                            ("received", "수금완료"),
                            ("overdue", "미수"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="등록자",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collections",
                        to="operation.saleslead",
                        verbose_name="영업기회",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operation_collections",
                        to="core.company",
                        verbose_name="워크스페이스(회사)",
                    ),
                ),
                (
                    "milestone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collections",
                        to="operation.revenuemilestone",
                        verbose_name="매출 계획",
                    ),
                ),
            ],
            options={
                "verbose_name": "수금",
                "verbose_name_plural": "수금 목록",
                "ordering": ["-due_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalesContractLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_id", models.IntegerField(verbose_name="계약 ID")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="등록자",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_links",
                        to="operation.saleslead",
                        verbose_name="영업기회",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operation_contract_links",
                        to="core.company",
                        verbose_name="워크스페이스(회사)",
                    ),
                ),
            ],
            options={
                "verbose_name": "계약 연결",
                "verbose_name_plural": "계약 연결 목록",
                "ordering": ["-created_at"],
                "unique_together": {("lead", "contract_id")},
            },
        ),
        migrations.CreateModel(
            name="Tender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="입찰명")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("notice_url", models.URLField(blank=True, verbose_name="공고 URL")),
                (
                    "deadline",
                    models.DateTimeField(blank=True, null=True, verbose_name="마감일"),
                ),
                (
                    "bond_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=15,
                        null=True,
                        verbose_name="보증금",
                    ),
                ),
                (
                    "documents",
                    models.JSONField(blank=True, default=list, verbose_name="제출서류"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "진행중"),
                            ("submitted", "제출완료"),
                            ("won", "낙찰"),
                            ("lost", "탈락"),
                            ("closed", "마감"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="제출일"),
                ),
                ("result_note", models.TextField(blank=True, verbose_name="결과 비고")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="등록자",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tenders",
                        to="operation.saleslead",
                        verbose_name="영업기회",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operation_tenders",
                        to="core.company",
                        verbose_name="워크스페이스(회사)",
                    ),
                ),
            ],
            options={
                "verbose_name": "입찰",
                "verbose_name_plural": "입찰 목록",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "deadline"],
                        name="operation_t_workspa_778101_idx",
                    )
                ],
            },
        ),
    ]
