# Generated by Django 6.0.1 on 2026-01-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operation", "0003_customercompany_owner_customercompany_status_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leadactivity",
            options={
                "ordering": ["-activity_date", "-created_at"],
                "verbose_name": "활동 로그",
                "verbose_name_plural": "활동 로그 목록",
            },
        ),
        migrations.AddField(
            model_name="leadactivity",
            name="activity_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="활동 날짜"),
        ),
        migrations.AddField(
            model_name="leadactivity",
            name="show_on_calendar",
            field=models.BooleanField(default=False, verbose_name="캘린더 표시"),
        ),
    ]
