# Generated by Django 6.0.1 on 2026-01-27 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("operation", "0004_alter_leadactivity_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leadactivity",
            name="show_on_calendar",
        ),
    ]
