# Generated by Django 6.0.1 on 2026-01-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operation", "0005_remove_leadactivity_show_on_calendar"),
    ]

    operations = [
        migrations.AddField(
            model_name="customercontact",
            name="priority",
            field=models.CharField(
                choices=[("high", "상"), ("medium", "중"), ("low", "하")],
                default="medium",
                max_length=10,
                verbose_name="우선순위",
            ),
        ),
    ]
