# Generated by Django 6.0.1 on 2026-01-27 23:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operation", "0006_customercontact_priority"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quoteitem",
            old_name="notes",
            new_name="remarks",
        ),
        migrations.AddField(
            model_name="quote",
            name="cc_email",
            field=models.CharField(
                blank=True,
                help_text="콤마로 구분",
                max_length=500,
                verbose_name="참조 이메일",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="customer_notes",
            field=models.TextField(
                blank=True, help_text="견적서 PDF/메일에 포함", verbose_name="고객 비고"
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="delivery_terms",
            field=models.CharField(blank=True, max_length=200, verbose_name="납품기한"),
        ),
        migrations.AddField(
            model_name="quote",
            name="internal_notes",
            field=models.TextField(
                blank=True, help_text="고객에게 노출되지 않음", verbose_name="내부 메모"
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="issue_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="견적일자"
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="payment_method",
            field=models.CharField(blank=True, max_length=200, verbose_name="결제조건"),
        ),
        migrations.AddField(
            model_name="quote",
            name="recipient_company",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="수신 회사명"
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="recipient_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="수신 이메일"
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="recipient_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="수신자명"),
        ),
        migrations.AddField(
            model_name="quote",
            name="revision",
            field=models.IntegerField(default=1, verbose_name="리비전"),
        ),
        migrations.AddField(
            model_name="quote",
            name="rounding_rule",
            field=models.CharField(
                choices=[
                    ("round", "반올림"),
                    ("floor", "절사(내림)"),
                    ("ceil", "올림"),
                ],
                default="floor",
                max_length=20,
                verbose_name="단수처리",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="rounding_unit",
            field=models.IntegerField(
                default=10, help_text="1, 10, 100, 1000 등", verbose_name="절사단위"
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="show_notes_on_separate_page",
            field=models.BooleanField(
                default=False, verbose_name="비고 별도페이지 인쇄"
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="tax_mode",
            field=models.CharField(
                choices=[
                    ("exclusive", "VAT 별도"),
                    ("inclusive", "VAT 포함"),
                    ("exempt", "면세/비과세"),
                ],
                default="exclusive",
                max_length=20,
                verbose_name="과세구분",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="validity_days",
            field=models.IntegerField(
                default=30, help_text="견적일로부터 N일간 유효", verbose_name="유효일수"
            ),
        ),
        migrations.AddField(
            model_name="quoteitem",
            name="discount_rate",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="할인율"
            ),
        ),
        migrations.AddField(
            model_name="quoteitem",
            name="is_discount_line",
            field=models.BooleanField(default=False, verbose_name="할인행 여부"),
        ),
        migrations.AddField(
            model_name="quoteitem",
            name="section",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="구분/섹션"
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="notes",
            field=models.TextField(blank=True, verbose_name="비고(Legacy)"),
        ),
        migrations.AlterField(
            model_name="quote",
            name="terms",
            field=models.TextField(blank=True, verbose_name="거래조건(기존)"),
        ),
    ]
