# Generated by Django 6.0.1 on 2026-01-28 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operation", "0007_rename_notes_quoteitem_remarks_quote_cc_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quote",
            name="cc_email",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="internal_notes",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="payment_method",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="recipient_company",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="recipient_email",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="recipient_name",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="rounding_rule",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="show_notes_on_separate_page",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="validity_days",
        ),
        migrations.RemoveField(
            model_name="quoteitem",
            name="is_discount_line",
        ),
        migrations.RemoveField(
            model_name="quoteitem",
            name="section",
        ),
        migrations.AddField(
            model_name="quote",
            name="cc_contacts",
            field=models.ManyToManyField(
                blank=True,
                related_name="cc_quotes",
                to="operation.customercontact",
                verbose_name="참조 담당자",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="internal_memo",
            field=models.TextField(
                blank=True,
                help_text="내부 참고용 메모 (PDF 미노출)",
                verbose_name="내부 메모",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="payment_terms",
            field=models.TextField(blank=True, verbose_name="대금지불조건"),
        ),
        migrations.AddField(
            model_name="quote",
            name="rounding_method",
            field=models.CharField(
                choices=[("floor", "절사"), ("round", "반올림"), ("ceil", "절상")],
                default="floor",
                max_length=10,
                verbose_name="라운딩 방법",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="seal_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="quotes/seals/",
                verbose_name="직인/서명",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="supplier_address",
            field=models.TextField(blank=True, verbose_name="공급자 주소"),
        ),
        migrations.AddField(
            model_name="quote",
            name="supplier_biz_no",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="공급자 사업자번호"
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="supplier_ceo_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="공급자 대표자명"
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="supplier_company_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="공급자 회사명"
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="supplier_contact_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="공급자 담당자"
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="supplier_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="공급자 이메일"
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="supplier_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="공급자 전화"
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="to_display_name",
            field=models.CharField(
                blank=True,
                help_text="예: (주)삼안 대표이사 귀하",
                max_length=200,
                verbose_name="수신 표기명",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="valid_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="validity_type='duration' 시 사용",
                null=True,
                verbose_name="유효일수",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="validity_type",
            field=models.CharField(
                choices=[("date", "날짜 지정"), ("duration", "기간 지정")],
                default="date",
                max_length=10,
                verbose_name="유효기간 유형",
            ),
        ),
        migrations.AddField(
            model_name="quoteitem",
            name="category",
            field=models.CharField(
                blank=True,
                help_text="섹션명 또는 카테고리",
                max_length=100,
                verbose_name="구분",
            ),
        ),
        migrations.AddField(
            model_name="quoteitem",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=15, verbose_name="할인액"
            ),
        ),
        migrations.AddField(
            model_name="quoteitem",
            name="line_type",
            field=models.CharField(
                choices=[
                    ("normal", "일반"),
                    ("discount", "할인"),
                    ("subtotal", "소계"),
                ],
                default="normal",
                max_length=10,
                verbose_name="라인 유형",
            ),
        ),
        migrations.AddField(
            model_name="quoteitem",
            name="notes",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="비고(레거시)"
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="customer_notes",
            field=models.TextField(
                blank=True, help_text="PDF에 노출되는 비고", verbose_name="고객용 비고"
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="delivery_terms",
            field=models.TextField(blank=True, verbose_name="납기 조건"),
        ),
        migrations.AlterField(
            model_name="quote",
            name="issue_date",
            field=models.DateField(blank=True, null=True, verbose_name="견적일자"),
        ),
        migrations.AlterField(
            model_name="quote",
            name="notes",
            field=models.TextField(blank=True, verbose_name="비고(레거시)"),
        ),
        migrations.AlterField(
            model_name="quote",
            name="revision",
            field=models.PositiveIntegerField(default=1, verbose_name="리비전"),
        ),
        migrations.AlterField(
            model_name="quote",
            name="rounding_unit",
            field=models.PositiveIntegerField(
                default=1, help_text="예: 1000 (천원단위)", verbose_name="라운딩 단위"
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="tax_mode",
            field=models.CharField(
                choices=[
                    ("exclusive", "VAT 별도"),
                    ("inclusive", "VAT 포함"),
                    ("exempt", "면세"),
                ],
                default="exclusive",
                max_length=10,
                verbose_name="세금 유형",
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="terms",
            field=models.TextField(blank=True, verbose_name="거래조건"),
        ),
        migrations.AlterField(
            model_name="quoteitem",
            name="description",
            field=models.TextField(blank=True, verbose_name="상세설명/내용"),
        ),
        migrations.AlterField(
            model_name="quoteitem",
            name="discount_rate",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="할인율(%)"
            ),
        ),
        migrations.AlterField(
            model_name="quoteitem",
            name="remarks",
            field=models.TextField(
                blank=True, help_text="멀티라인 비고", verbose_name="비고"
            ),
        ),
    ]
