# Generated by Django 6.0.1 on 2026-01-28 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "operation",
            "0008_remove_quote_cc_email_remove_quote_internal_notes_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quote",
            name="cc_contacts",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="delivery_terms",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="rounding_method",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="seal_image",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="supplier_address",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="supplier_biz_no",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="supplier_ceo_name",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="supplier_company_name",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="supplier_contact_name",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="supplier_email",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="supplier_phone",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="to_display_name",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="valid_days",
        ),
        migrations.RemoveField(
            model_name="quoteitem",
            name="discount_amount",
        ),
        migrations.RemoveField(
            model_name="quoteitem",
            name="discount_rate",
        ),
        migrations.RemoveField(
            model_name="quoteitem",
            name="line_type",
        ),
        migrations.AddField(
            model_name="quote",
            name="attachment_label",
            field=models.CharField(blank=True, max_length=50, verbose_name="붙임 구분"),
        ),
        migrations.AddField(
            model_name="quote",
            name="cc_recipients",
            field=models.TextField(blank=True, verbose_name="참조"),
        ),
        migrations.AddField(
            model_name="quote",
            name="delivery_date",
            field=models.DateField(blank=True, null=True, verbose_name="납품예정일"),
        ),
        migrations.AddField(
            model_name="quote",
            name="delivery_note",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="납기 비고"
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="recipient_label",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="수신 표시명"
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="rounding_type",
            field=models.CharField(
                choices=[
                    ("floor", "절사(내림)"),
                    ("round", "반올림"),
                    ("ceil", "올림"),
                ],
                default="floor",
                max_length=10,
                verbose_name="라운딩 타입",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="show_notes_on_separate_page",
            field=models.BooleanField(default=False, verbose_name="비고 별도 페이지"),
        ),
        migrations.AddField(
            model_name="quote",
            name="total_amount_korean",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="금액(한글)"
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="validity_days",
            field=models.PositiveIntegerField(default=30, verbose_name="유효기간(일)"),
        ),
        migrations.AddField(
            model_name="quoteitem",
            name="discount_type",
            field=models.CharField(
                choices=[
                    ("none", "할인 없음"),
                    ("percent", "퍼센트"),
                    ("amount", "금액"),
                ],
                default="none",
                max_length=10,
                verbose_name="할인 타입",
            ),
        ),
        migrations.AddField(
            model_name="quoteitem",
            name="discount_value",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="할인 값"
            ),
        ),
        migrations.AddField(
            model_name="quoteitem",
            name="is_discount_item",
            field=models.BooleanField(default=False, verbose_name="할인 표시행"),
        ),
        migrations.AlterField(
            model_name="quote",
            name="customer_notes",
            field=models.TextField(blank=True, verbose_name="고객 비고"),
        ),
        migrations.AlterField(
            model_name="quote",
            name="internal_memo",
            field=models.TextField(blank=True, verbose_name="내부 메모"),
        ),
        migrations.AlterField(
            model_name="quote",
            name="payment_terms",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="대금지불조건"
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="revision",
            field=models.PositiveIntegerField(default=1, verbose_name="버전"),
        ),
        migrations.AlterField(
            model_name="quote",
            name="rounding_unit",
            field=models.PositiveIntegerField(default=1000, verbose_name="라운딩 단위"),
        ),
        migrations.AlterField(
            model_name="quote",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "작성중"),
                    ("issued", "발행됨"),
                    ("sent", "발송됨"),
                    ("accepted", "수락"),
                    ("rejected", "거절"),
                    ("expired", "만료"),
                ],
                default="draft",
                max_length=10,
                verbose_name="상태",
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="tax_mode",
            field=models.CharField(
                choices=[
                    ("exclusive", "VAT 별도"),
                    ("inclusive", "VAT 포함"),
                    ("exempt", "면세"),
                ],
                default="exclusive",
                max_length=10,
                verbose_name="VAT 모드",
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="validity_type",
            field=models.CharField(
                choices=[("date", "날짜 지정"), ("days", "기간(일수)")],
                default="days",
                max_length=10,
                verbose_name="유효기간 타입",
            ),
        ),
        migrations.AlterField(
            model_name="quoteitem",
            name="category",
            field=models.CharField(blank=True, max_length=100, verbose_name="구분"),
        ),
        migrations.AlterField(
            model_name="quoteitem",
            name="description",
            field=models.TextField(blank=True, verbose_name="상세설명"),
        ),
        migrations.AlterField(
            model_name="quoteitem",
            name="remarks",
            field=models.CharField(blank=True, max_length=200, verbose_name="비고"),
        ),
    ]
