# Generated by Django 6.0.1 on 2026-01-16 07:53

import django.db.models.deletion
import project.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="프로젝트 코드"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="프로젝트 명칭"),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명/메모")),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="시작일"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="종료일"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("preparing", "준비중"),
                            ("in_progress", "진행중"),
                            ("completed", "완료"),
                            ("on_hold", "보류"),
                        ],
                        default="preparing",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "progress",
                    models.PositiveIntegerField(
                        default=0, help_text="0~100%", verbose_name="진행률"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="공개 여부"),
                ),
                (
                    "is_important",
                    models.BooleanField(default=False, verbose_name="중요 표시"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="관리자",
                    ),
                ),
            ],
            options={
                "verbose_name": "프로젝트",
                "verbose_name_plural": "프로젝트",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "관리자"),
                            ("member", "멤버"),
                            ("viewer", "뷰어"),
                        ],
                        default="member",
                        max_length=20,
                        verbose_name="역할",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성 상태"),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="참여일"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="project.project",
                        verbose_name="프로젝트",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "프로젝트 멤버",
                "verbose_name_plural": "프로젝트 멤버",
                "ordering": ["joined_at"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="업무명")),
                ("content", models.TextField(blank=True, verbose_name="내용")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "대기"),
                            ("in_progress", "진행중"),
                            ("completed", "완료"),
                            ("on_hold", "보류"),
                        ],
                        default="waiting",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("urgent", "긴급"),
                            ("high", "높음"),
                            ("normal", "보통"),
                            ("low", "낮음"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="우선순위",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="시작일"),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="마감일"),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="읽음 여부"),
                ),
                (
                    "is_disabled",
                    models.BooleanField(default=False, verbose_name="사용중지"),
                ),
                (
                    "is_important",
                    models.BooleanField(default=False, verbose_name="중요 표시"),
                ),
                (
                    "notify_enabled",
                    models.BooleanField(default=True, verbose_name="알림 활성화"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="담당자",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="관리자",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="null이면 미분류",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="project.project",
                        verbose_name="프로젝트",
                    ),
                ),
            ],
            options={
                "verbose_name": "업무",
                "verbose_name_plural": "업무",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "생성됨"),
                            ("updated", "수정됨"),
                            ("deleted", "삭제됨"),
                            ("status_changed", "상태 변경"),
                            ("assigned", "담당자 지정"),
                            ("commented", "댓글 작성"),
                            ("file_uploaded", "파일 업로드"),
                            ("member_added", "멤버 추가"),
                            ("member_removed", "멤버 제거"),
                        ],
                        max_length=30,
                        verbose_name="활동 유형",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="일시"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="project.project",
                        verbose_name="프로젝트",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="project.task",
                        verbose_name="업무",
                    ),
                ),
            ],
            options={
                "verbose_name": "활동 로그",
                "verbose_name_plural": "활동 로그",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=project.models.task_attachment_path,
                        verbose_name="파일",
                    ),
                ),
                (
                    "original_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="원본 파일명"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveBigIntegerField(default=0, verbose_name="파일 크기"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="업로드일"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="project.task",
                        verbose_name="업무",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="업로더",
                    ),
                ),
            ],
            options={
                "verbose_name": "첨부파일",
                "verbose_name_plural": "첨부파일",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="project.task",
                        verbose_name="업무",
                    ),
                ),
            ],
            options={
                "verbose_name": "댓글",
                "verbose_name_plural": "댓글",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskWatcher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="추가일"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watchers",
                        to="project.task",
                        verbose_name="업무",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watching_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="참조인",
                    ),
                ),
            ],
            options={
                "verbose_name": "참조인",
                "verbose_name_plural": "참조인",
            },
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["status"], name="project_pro_status_d7ebb2_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["is_public"], name="project_pro_is_publ_a73f4e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["-updated_at"], name="project_pro_updated_4d23df_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectmember",
            unique_together={("project", "user")},
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["project", "status"], name="project_tas_project_4b14b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["assignee", "status"], name="project_tas_assigne_550b22_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["-updated_at"], name="project_tas_updated_b0ce4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["is_disabled"], name="project_tas_is_disa_c4c0f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["project", "-created_at"], name="project_act_project_89bf84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["task", "-created_at"], name="project_act_task_id_59d004_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="taskwatcher",
            unique_together={("task", "user")},
        ),
    ]
