# Generated by Django 6.0.1 on 2026-01-16 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimesheetEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_date", models.DateField(verbose_name="작업일")),
                (
                    "hours",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="소수점 1자리까지 (예: 1.5시간)",
                        max_digits=4,
                        verbose_name="시간",
                    ),
                ),
                ("memo", models.TextField(blank=True, verbose_name="메모")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timesheet_entries",
                        to="project.project",
                        verbose_name="프로젝트",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timesheet_entries",
                        to="project.task",
                        verbose_name="업무",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timesheet_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "타임시트",
                "verbose_name_plural": "타임시트",
                "ordering": ["-work_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "work_date"],
                        name="project_tim_user_id_edcfe0_idx",
                    ),
                    models.Index(
                        fields=["project", "work_date"],
                        name="project_tim_project_83ad7f_idx",
                    ),
                ],
                "unique_together": {("user", "project", "task", "work_date")},
            },
        ),
        migrations.CreateModel(
            name="WorkDiaryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="날짜")),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_diary_entries",
                        to="project.project",
                        verbose_name="프로젝트",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_diary_entries",
                        to="project.task",
                        verbose_name="업무",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_diary_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "업무일지",
                "verbose_name_plural": "업무일지",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="project_wor_user_id_9b0437_idx"
                    )
                ],
            },
        ),
    ]
