# Generated by Django 6.0.1 on 2026-01-11 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="양식명")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "category",
                    models.CharField(
                        default="일반", max_length=50, verbose_name="분류"
                    ),
                ),
                (
                    "content_template",
                    models.TextField(
                        blank=True,
                        help_text="HTML 또는 Markdown 형식",
                        verbose_name="내용 템플릿",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "결재 양식",
                "verbose_name_plural": "결재 양식",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("content", models.TextField(blank=True, verbose_name="내용")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "임시저장"),
                            ("pending", "결재 중"),
                            ("approved", "승인"),
                            ("rejected", "반려"),
                            ("canceled", "취소"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("normal", "일반"),
                            ("urgent", "긴급"),
                            ("important", "중요"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="우선순위",
                    ),
                ),
                (
                    "attachment_count",
                    models.PositiveIntegerField(default=0, verbose_name="첨부파일 수"),
                ),
                (
                    "drafted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="기안일"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="제출일"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="완료일"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authored_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="기안자",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="approval.documenttemplate",
                        verbose_name="양식",
                    ),
                ),
            ],
            options={
                "verbose_name": "결재 문서",
                "verbose_name_plural": "결재 문서",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("submit", "제출"),
                            ("approve", "승인"),
                            ("reject", "반려"),
                            ("cancel", "취소"),
                            ("return", "회수"),
                            ("comment", "의견 추가"),
                        ],
                        max_length=20,
                        verbose_name="액션",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="의견")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="처리자",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="approval.document",
                        verbose_name="문서",
                    ),
                ),
            ],
            options={
                "verbose_name": "결재 이력",
                "verbose_name_plural": "결재 이력",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="순서")),
                (
                    "approval_type",
                    models.CharField(
                        choices=[
                            ("approval", "결재"),
                            ("agreement", "합의"),
                            ("reference", "참조"),
                        ],
                        default="approval",
                        max_length=20,
                        verbose_name="결재 유형",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "대기"),
                            ("pending", "결재 대기"),
                            ("approved", "승인"),
                            ("rejected", "반려"),
                            ("skipped", "건너뜀"),
                        ],
                        default="waiting",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="의견")),
                (
                    "acted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="처리일"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="결재자",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_lines",
                        to="approval.document",
                        verbose_name="문서",
                    ),
                ),
            ],
            options={
                "verbose_name": "결재선",
                "verbose_name_plural": "결재선",
                "ordering": ["document", "order"],
                "unique_together": {("document", "order")},
            },
        ),
    ]
