# Generated by Django 6.0.1 on 2026-01-13 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="attachment_count",
        ),
        migrations.AddField(
            model_name="approvalline",
            name="is_read",
            field=models.BooleanField(default=False, verbose_name="열람 여부"),
        ),
        migrations.AddField(
            model_name="approvalline",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="열람일"),
        ),
        migrations.AddField(
            model_name="document",
            name="document_number",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="문서번호",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="form_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="양식 필드 값",
                verbose_name="양식 데이터",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="is_read",
            field=models.BooleanField(default=False, verbose_name="읽음 여부"),
        ),
        migrations.AddField(
            model_name="document",
            name="preservation_period",
            field=models.IntegerField(
                choices=[(1, "1년"), (3, "3년"), (5, "5년"), (10, "10년"), (0, "영구")],
                default=5,
                verbose_name="보존기간",
            ),
        ),
        migrations.AddField(
            model_name="documenttemplate",
            name="form_fields",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="동적 양식 필드 정의",
                verbose_name="양식 필드",
            ),
        ),
        migrations.AlterField(
            model_name="documenttemplate",
            name="category",
            field=models.CharField(
                choices=[
                    ("general", "일반"),
                    ("leave", "휴가"),
                    ("expense", "지출"),
                    ("official", "공문"),
                    ("report", "보고"),
                    ("etc", "기타"),
                ],
                default="general",
                max_length=50,
                verbose_name="분류",
            ),
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="approval/attachments/%Y/%m/", verbose_name="첨부파일"
                    ),
                ),
                (
                    "filename",
                    models.CharField(max_length=255, verbose_name="원본 파일명"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, verbose_name="파일 크기(bytes)"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="업로드일"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="approval.document",
                        verbose_name="문서",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_attachments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="업로더",
                    ),
                ),
            ],
            options={
                "verbose_name": "첨부파일",
                "verbose_name_plural": "첨부파일",
                "ordering": ["uploaded_at"],
            },
        ),
    ]
