# Generated by Django 6.0.1 on 2026-02-23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("approval", "0002_remove_document_attachment_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="priority",
        ),
    ]
