# Generated by Django 6.0.1 on 2026-02-23

from django.db import migrations, models


def copy_content_template_to_content(apps, schema_editor):
    DocumentTemplate = apps.get_model("approval", "DocumentTemplate")
    for template in DocumentTemplate.objects.all():
        if not getattr(template, "content", "") and template.content_template:
            template.content = template.content_template
            template.save(update_fields=["content"])


class Migration(migrations.Migration):

    dependencies = [
        ("approval", "0003_remove_document_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="documenttemplate",
            name="content",
            field=models.TextField(blank=True, verbose_name="내용"),
        ),
        migrations.RunPython(
            copy_content_template_to_content,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="documenttemplate",
            name="description",
        ),
        migrations.RemoveField(
            model_name="documenttemplate",
            name="content_template",
        ),
        migrations.RemoveField(
            model_name="documenttemplate",
            name="form_fields",
        ),
    ]
