# Generated by Django 6.0.1 on 2026-02-23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("approval", "0004_documenttemplate_simplify_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalLinePreset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="결재선 이름")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_line_presets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="소유자",
                    ),
                ),
            ],
            options={
                "verbose_name": "결재선 프리셋",
                "verbose_name_plural": "결재선 프리셋",
                "ordering": ["-updated_at", "-id"],
                "unique_together": {("owner", "name")},
            },
        ),
        migrations.CreateModel(
            name="ApprovalLinePresetItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="순서")),
                (
                    "approval_type",
                    models.CharField(
                        choices=[("approval", "결재"), ("agreement", "합의"), ("reference", "참조")],
                        default="approval",
                        max_length=20,
                        verbose_name="결재 유형",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_line_preset_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="결재자",
                    ),
                ),
                (
                    "preset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="approval.approvallinepreset",
                        verbose_name="결재선 프리셋",
                    ),
                ),
            ],
            options={
                "verbose_name": "결재선 프리셋 항목",
                "verbose_name_plural": "결재선 프리셋 항목",
                "ordering": ["preset", "order"],
                "unique_together": {("preset", "order")},
            },
        ),
    ]
