# Generated by Django 6.0.1 on 2026-02-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval", "0005_approvallinepreset_and_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="documenttemplate",
            name="template_type",
            field=models.CharField(
                choices=[("official", "공문 양식"), ("approval", "결재 양식")],
                default="official",
                max_length=20,
                verbose_name="양식 유형",
            ),
        ),
    ]
