# Generated by Django 6.0.1 on 2026-01-13 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "is_draft",
                    models.BooleanField(default=False, verbose_name="임시저장"),
                ),
                (
                    "is_to_self",
                    models.BooleanField(default=False, verbose_name="내게 쓴 글"),
                ),
                (
                    "is_starred",
                    models.BooleanField(default=False, verbose_name="중요 표시"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="삭제됨"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_sent_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="발신자",
                    ),
                ),
            ],
            options={
                "verbose_name": "업무연락",
                "verbose_name_plural": "업무연락",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="내용")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="contact.message",
                        verbose_name="메시지",
                    ),
                ),
            ],
            options={
                "verbose_name": "댓글",
                "verbose_name_plural": "댓글",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="contact/attachments/%Y/%m/", verbose_name="파일"
                    ),
                ),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="원본 파일명"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(default=0, verbose_name="파일 크기"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="contact.message",
                        verbose_name="메시지",
                    ),
                ),
            ],
            options={
                "verbose_name": "첨부파일",
                "verbose_name_plural": "첨부파일",
            },
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="읽음")),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="읽은 시간"
                    ),
                ),
                (
                    "is_starred",
                    models.BooleanField(default=False, verbose_name="중요 표시"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="삭제됨"),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="contact.message",
                        verbose_name="메시지",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="수신자",
                    ),
                ),
            ],
            options={
                "verbose_name": "수신자",
                "verbose_name_plural": "수신자",
                "unique_together": {("message", "recipient")},
            },
        ),
    ]
