# Generated by Django 6.0.1 on 2026-01-12 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="게시판 이름")),
                ("slug", models.SlugField(unique=True, verbose_name="슬러그")),
                (
                    "board_type",
                    models.CharField(
                        choices=[
                            ("notice", "공지사항"),
                            ("general", "일반 게시판"),
                            ("qna", "Q&A"),
                            ("archive", "자료실"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="게시판 유형",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                (
                    "can_write_all",
                    models.BooleanField(default=True, verbose_name="전체 쓰기 가능"),
                ),
                (
                    "can_comment",
                    models.BooleanField(default=True, verbose_name="댓글 허용"),
                ),
                (
                    "can_attach",
                    models.BooleanField(default=True, verbose_name="첨부파일 허용"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="정렬 순서"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "게시판",
                "verbose_name_plural": "게시판",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "is_notice",
                    models.BooleanField(default=False, verbose_name="공지 고정"),
                ),
                (
                    "is_secret",
                    models.BooleanField(default=False, verbose_name="비밀글"),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="조회수"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="board.board",
                        verbose_name="게시판",
                    ),
                ),
            ],
            options={
                "verbose_name": "게시글",
                "verbose_name_plural": "게시글",
                "ordering": ["-is_notice", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="내용")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="board.comment",
                        verbose_name="상위 댓글",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="board.post",
                        verbose_name="게시글",
                    ),
                ),
            ],
            options={
                "verbose_name": "댓글",
                "verbose_name_plural": "댓글",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="board/attachments/%Y/%m/", verbose_name="파일"
                    ),
                ),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="원본 파일명"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(default=0, verbose_name="파일 크기"),
                ),
                (
                    "download_count",
                    models.PositiveIntegerField(default=0, verbose_name="다운로드 수"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="board.post",
                        verbose_name="게시글",
                    ),
                ),
            ],
            options={
                "verbose_name": "첨부파일",
                "verbose_name_plural": "첨부파일",
            },
        ),
    ]
