# Generated by Django 6.0.1 on 2026-01-13 08:16

import board.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="author",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="post",
        ),
        migrations.AlterModelOptions(
            name="board",
            options={
                "ordering": ["created_at"],
                "verbose_name": "게시판",
                "verbose_name_plural": "게시판",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "게시글",
                "verbose_name_plural": "게시글 목록",
            },
        ),
        migrations.AlterUniqueTogether(
            name="board",
            unique_together={("name",)},
        ),
        migrations.RemoveField(
            model_name="post",
            name="author",
        ),
        migrations.RemoveField(
            model_name="post",
            name="is_notice",
        ),
        migrations.RemoveField(
            model_name="post",
            name="is_secret",
        ),
        migrations.RemoveField(
            model_name="post",
            name="view_count",
        ),
        migrations.AddField(
            model_name="board",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_boards",
                to="board.board",
                verbose_name="상위 게시판",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="writer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="작성자",
            ),
        ),
        migrations.AlterField(
            model_name="board",
            name="board_type",
            field=models.CharField(
                choices=[("work", "업무 관련 게시판"), ("free", "자유 게시판")],
                default="work",
                max_length=10,
                verbose_name="게시판 유형",
            ),
        ),
        migrations.AlterField(
            model_name="board",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="설명"),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
        ),
        migrations.AlterField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정일"),
        ),
        migrations.CreateModel(
            name="PostFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=board.models.post_file_path, verbose_name="첨부파일"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="board.post",
                        verbose_name="게시글",
                    ),
                ),
            ],
            options={
                "verbose_name": "첨부파일",
                "verbose_name_plural": "첨부파일",
            },
        ),
        migrations.DeleteModel(
            name="Attachment",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.RemoveField(
            model_name="board",
            name="can_attach",
        ),
        migrations.RemoveField(
            model_name="board",
            name="can_comment",
        ),
        migrations.RemoveField(
            model_name="board",
            name="can_write_all",
        ),
        migrations.RemoveField(
            model_name="board",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="board",
            name="order",
        ),
        migrations.RemoveField(
            model_name="board",
            name="slug",
        ),
    ]
