# Generated by Django 6.0.1 on 2026-01-12 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="회의실명")),
                (
                    "location",
                    models.CharField(blank=True, max_length=200, verbose_name="위치"),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(default=10, verbose_name="수용 인원"),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="사용 가능"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6", max_length=20, verbose_name="색상"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "회의실",
                "verbose_name_plural": "회의실",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("personal", "개인 일정"),
                            ("team", "팀 일정"),
                            ("company", "전사 일정"),
                            ("meeting", "회의"),
                        ],
                        default="personal",
                        max_length=20,
                        verbose_name="일정 유형",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="시작 시간")),
                ("end_time", models.DateTimeField(verbose_name="종료 시간")),
                ("is_all_day", models.BooleanField(default=False, verbose_name="종일")),
                (
                    "location",
                    models.CharField(blank=True, max_length=200, verbose_name="장소"),
                ),
                (
                    "is_recurring",
                    models.BooleanField(default=False, verbose_name="반복 일정"),
                ),
                (
                    "recurrence_rule",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="반복 규칙"
                    ),
                ),
                (
                    "reminder_minutes",
                    models.PositiveIntegerField(
                        default=30, verbose_name="알림 (분 전)"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6", max_length=20, verbose_name="색상"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attendees",
                    models.ManyToManyField(
                        blank=True,
                        related_name="attending_schedules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="참석자",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
                (
                    "meeting_room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedules",
                        to="meeting.meetingroom",
                        verbose_name="회의실",
                    ),
                ),
            ],
            options={
                "verbose_name": "일정",
                "verbose_name_plural": "일정",
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleAttendee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "response",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("accepted", "수락"),
                            ("declined", "거절"),
                            ("tentative", "미정"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="응답",
                    ),
                ),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="응답 시간"
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendee_responses",
                        to="meeting.schedule",
                        verbose_name="일정",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_responses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "참석 응답",
                "verbose_name_plural": "참석 응답",
                "unique_together": {("schedule", "user")},
            },
        ),
    ]
