# Generated by Codex on 2026-01-16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meeting", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedule",
            old_name="author",
            new_name="owner",
        ),
        migrations.RenameField(
            model_name="schedule",
            old_name="attendees",
            new_name="participants",
        ),
    ]
