# Generated by Codex on 2026-01-16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def migrate_schedule_data(apps, schema_editor):
    Schedule = apps.get_model("meeting", "Schedule")
    MeetingRoom = apps.get_model("meeting", "MeetingRoom")
    room_names = dict(MeetingRoom.objects.values_list("id", "name"))

    for schedule in Schedule.objects.order_by("pk").iterator():
        memo = schedule.memo or ""
        additions = []

        if schedule.location:
            additions.append(f"장소: {schedule.location}")

        if schedule.meeting_room_id:
            room_name = room_names.get(schedule.meeting_room_id)
            if room_name:
                additions.append(f"회의실: {room_name}")
            else:
                additions.append(f"회의실 ID: {schedule.meeting_room_id}")

        scope_changed = False
        if schedule.scope in ("team", "meeting"):
            additions.append(f"기존 일정 유형: {schedule.scope}")
            schedule.scope = "company"
            scope_changed = True

        memo_changed = False
        if additions:
            if memo:
                memo = memo.rstrip()
                memo = f"{memo}\n" + "\n".join(additions)
            else:
                memo = "\n".join(additions)
            schedule.memo = memo
            memo_changed = True

        if memo_changed or scope_changed:
            update_fields = []
            if memo_changed:
                update_fields.append("memo")
            if scope_changed:
                update_fields.append("scope")
            schedule.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("meeting", "0002_rename_schedule_owner_participants"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedule",
            old_name="description",
            new_name="memo",
        ),
        migrations.RenameField(
            model_name="schedule",
            old_name="schedule_type",
            new_name="scope",
        ),
        migrations.RenameField(
            model_name="schedule",
            old_name="start_time",
            new_name="start",
        ),
        migrations.RenameField(
            model_name="schedule",
            old_name="end_time",
            new_name="end",
        ),
        migrations.AddField(
            model_name="schedule",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="core.company",
                verbose_name="회사",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_schedules",
                to=settings.AUTH_USER_MODEL,
                verbose_name="작성자",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                related_name="schedule_participations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="참여자",
            ),
        ),
        migrations.RunPython(migrate_schedule_data, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="schedule",
            name="location",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="meeting_room",
        ),
        migrations.AlterField(
            model_name="schedule",
            name="memo",
            field=models.TextField(blank=True, verbose_name="메모"),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="scope",
            field=models.CharField(
                choices=[("personal", "개인"), ("company", "회사")],
                db_index=True,
                default="personal",
                max_length=20,
                verbose_name="범위",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="start",
            field=models.DateTimeField(verbose_name="시작일시"),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="end",
            field=models.DateTimeField(blank=True, null=True, verbose_name="종료일시"),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="title",
            field=models.CharField(max_length=255, verbose_name="제목"),
        ),
        migrations.AlterModelOptions(
            name="schedule",
            options={
                "ordering": ["-start"],
                "verbose_name": "일정",
                "verbose_name_plural": "일정 목록",
            },
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(fields=["scope", "start"], name="meeting_schedule_scope_start_idx"),
        ),
        migrations.AddField(
            model_name="meetingroom",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="정렬 순서"),
        ),
        migrations.AddField(
            model_name="meetingroom",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name="meetingroom",
            options={
                "ordering": ["order", "name"],
                "verbose_name": "회의실",
                "verbose_name_plural": "회의실",
            },
        ),
    ]
