# Generated by Django 6.0.1 on 2026-01-16 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meeting", "0003_align_schedule_fields_preserve_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="제목")),
                ("schedule", models.DateTimeField(verbose_name="일정")),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("online", "온라인"),
                            ("offline_room", "오프라인(회의실)"),
                            ("offline_address", "오프라인(주소)"),
                        ],
                        db_index=True,
                        default="offline_address",
                        max_length=20,
                        verbose_name="장소 구분",
                    ),
                ),
                ("location", models.TextField(blank=True, verbose_name="장소")),
                ("agenda", models.TextField(blank=True, verbose_name="안건")),
                ("result", models.TextField(blank=True, verbose_name="회의 결과")),
                (
                    "is_urgent",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="긴급"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "회의",
                "verbose_name_plural": "회의 목록",
                "ordering": ["-schedule"],
            },
        ),
        migrations.CreateModel(
            name="MeetingParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "responded",
                    models.BooleanField(default=False, verbose_name="참여 응답 여부"),
                ),
                (
                    "is_attending",
                    models.BooleanField(default=False, verbose_name="참여"),
                ),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="응답 시간"
                    ),
                ),
            ],
            options={
                "verbose_name": "회의 참석자",
                "verbose_name_plural": "회의 참석자 목록",
            },
        ),
        migrations.RenameIndex(
            model_name="schedule",
            new_name="meeting_sch_scope_089a4b_idx",
            old_name="meeting_schedule_scope_start_idx",
        ),
        migrations.AddField(
            model_name="meeting",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_meetings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="작성자",
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="meeting_room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meetings",
                to="meeting.meetingroom",
                verbose_name="회의실",
            ),
        ),
        migrations.AddField(
            model_name="meetingparticipant",
            name="meeting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="meeting.meeting",
            ),
        ),
        migrations.AddField(
            model_name="meetingparticipant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meeting_attendances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(
                fields=["schedule"], name="meeting_mee_schedul_f302e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meetingparticipant",
            index=models.Index(
                fields=["meeting", "responded", "is_attending"],
                name="meeting_mee_meeting_f45558_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="meetingparticipant",
            index=models.Index(
                fields=["user", "responded", "is_attending"],
                name="meeting_mee_user_id_cb4017_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="meetingparticipant",
            unique_together={("meeting", "user")},
        ),
    ]
