# Generated by Django 6.0.1 on 2026-01-16 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("meeting", "0004_meeting_meetingparticipant_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="자원명")),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("room", "회의실"),
                            ("vehicle", "차량"),
                            ("equipment", "장비"),
                        ],
                        db_index=True,
                        default="room",
                        max_length=20,
                        verbose_name="자원유형",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=1, verbose_name="수용인원/좌석"
                    ),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=200, verbose_name="위치"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#10B981", max_length=20, verbose_name="색상"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="사용가능"),
                ),
                (
                    "requires_approval",
                    models.BooleanField(default=False, verbose_name="승인필요"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="정렬 순서"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "자원",
                "verbose_name_plural": "자원",
                "ordering": ["order", "name"],
            },
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="recurrence_rule",
        ),
        migrations.AddField(
            model_name="schedule",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("general", "일반"),
                    ("annual", "연차"),
                    ("monthly", "월차"),
                    ("half", "반차"),
                    ("meeting", "회의"),
                    ("trip", "출장"),
                ],
                db_index=True,
                default="general",
                max_length=20,
                verbose_name="일정 유형",
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="location",
            field=models.CharField(blank=True, max_length=255, verbose_name="장소"),
        ),
        migrations.AddField(
            model_name="schedule",
            name="recurrence_exception_date",
            field=models.DateField(blank=True, null=True, verbose_name="예외일"),
        ),
        migrations.AddField(
            model_name="schedule",
            name="recurrence_parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recurrence_instances",
                to="meeting.schedule",
                verbose_name="반복 원본",
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="rrule",
            field=models.TextField(
                blank=True,
                help_text="RFC 5545 형식: FREQ=WEEKLY;BYDAY=MO,WE;UNTIL=20260301",
                verbose_name="반복규칙(RRULE)",
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="status",
            field=models.CharField(
                choices=[("confirmed", "확정"), ("cancelled", "취소")],
                default="confirmed",
                max_length=20,
                verbose_name="상태",
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("private", "개인"),
                    ("organization", "조직"),
                    ("public", "전체"),
                ],
                default="private",
                max_length=20,
                verbose_name="공개범위",
            ),
        ),
        migrations.CreateModel(
            name="Calendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="캘린더명")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("all", "전체 일정"),
                            ("shared", "공유 일정"),
                            ("personal", "개인 일정"),
                            ("site", "현장일정"),
                            ("project", "프로젝트"),
                            ("development", "개발자회의 일정"),
                            ("resource", "자원예약"),
                        ],
                        db_index=True,
                        default="personal",
                        max_length=20,
                        verbose_name="분류",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6", max_length=20, verbose_name="색상"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="기본 캘린더"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="정렬 순서"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendars",
                        to="core.company",
                        verbose_name="회사",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_calendars",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="소유자",
                    ),
                ),
            ],
            options={
                "verbose_name": "캘린더",
                "verbose_name_plural": "캘린더",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="schedule",
            name="calendar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schedules",
                to="meeting.calendar",
                verbose_name="캘린더",
            ),
        ),
        migrations.CreateModel(
            name="ResourceReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField(verbose_name="시작")),
                ("end", models.DateTimeField(verbose_name="종료")),
                (
                    "purpose",
                    models.CharField(blank=True, max_length=255, verbose_name="목적"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "승인대기"),
                            ("approved", "승인"),
                            ("rejected", "반려"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="승인일시"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="비고")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_reservations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="승인자",
                    ),
                ),
                (
                    "reserved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_reservations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="예약자",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="meeting.resource",
                        verbose_name="자원",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_reservations",
                        to="meeting.schedule",
                        verbose_name="일정",
                    ),
                ),
            ],
            options={
                "verbose_name": "자원 예약",
                "verbose_name_plural": "자원 예약",
                "ordering": ["-start"],
                "indexes": [
                    models.Index(
                        fields=["resource", "start", "end"],
                        name="meeting_res_resourc_f321ad_idx",
                    ),
                    models.Index(
                        fields=["status"], name="meeting_res_status_9243fe_idx"
                    ),
                ],
            },
        ),
    ]
