# Generated by Django 6.0.1 on 2026-01-16 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("meeting", "0005_resource_remove_schedule_recurrence_rule_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="meeting",
            name="meeting_mee_schedul_f302e1_idx",
        ),
        migrations.AlterUniqueTogether(
            name="meetingparticipant",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="meetingparticipant",
            name="meeting_mee_meeting_f45558_idx",
        ),
        migrations.RemoveIndex(
            model_name="meetingparticipant",
            name="meeting_mee_user_id_cb4017_idx",
        ),
        migrations.AddField(
            model_name="resource",
            name="equipment",
            field=models.TextField(
                blank=True, help_text="보유 장비 목록", verbose_name="장비"
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="agenda",
            field=models.TextField(blank=True, verbose_name="안건"),
        ),
        migrations.AddField(
            model_name="schedule",
            name="is_urgent",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="긴급"
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="location_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "-"),
                    ("online", "온라인"),
                    ("offline_room", "오프라인(회의실)"),
                    ("offline_address", "오프라인(주소)"),
                ],
                default="",
                max_length=20,
                verbose_name="장소 구분",
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="meet_url",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="온라인 링크"
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="resource",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schedules",
                to="meeting.resource",
                verbose_name="회의실/자원",
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="result",
            field=models.TextField(blank=True, verbose_name="회의 결과"),
        ),
        migrations.AddField(
            model_name="scheduleattendee",
            name="is_attending",
            field=models.BooleanField(
                blank=True,
                help_text="True=참석, False=불참, None=미응답",
                null=True,
                verbose_name="참석 여부",
            ),
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(
                fields=["event_type", "start"], name="meeting_sch_event_t_8c2e23_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduleattendee",
            index=models.Index(
                fields=["schedule", "response"], name="meeting_sch_schedul_87d293_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduleattendee",
            index=models.Index(
                fields=["user", "response"], name="meeting_sch_user_id_a34006_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="meeting",
            name="author",
        ),
        migrations.RemoveField(
            model_name="meeting",
            name="meeting_room",
        ),
        migrations.RemoveField(
            model_name="meetingparticipant",
            name="meeting",
        ),
        migrations.RemoveField(
            model_name="meetingparticipant",
            name="user",
        ),
        migrations.DeleteModel(
            name="MeetingRoom",
        ),
        migrations.DeleteModel(
            name="Meeting",
        ),
        migrations.DeleteModel(
            name="MeetingParticipant",
        ),
    ]
