# Generated by Django 6.0.1 on 2026-01-16 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("meeting", "0006_remove_meeting_meeting_mee_schedul_f302e1_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="calendar",
            name="calendar_type",
            field=models.CharField(
                choices=[("system", "시스템"), ("custom", "사용자 정의")],
                db_index=True,
                default="system",
                max_length=20,
                verbose_name="캘린더 타입",
            ),
        ),
        migrations.AddField(
            model_name="calendar",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_calendars",
                to="meeting.calendar",
                verbose_name="상위 캘린더",
            ),
        ),
        migrations.AlterField(
            model_name="calendar",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("all", "전체 일정"),
                    ("shared", "공유 일정"),
                    ("personal", "개인 일정"),
                    ("headquarters", "본사일정"),
                ],
                db_index=True,
                default="personal",
                max_length=20,
                verbose_name="분류",
            ),
        ),
        migrations.AddIndex(
            model_name="calendar",
            index=models.Index(
                fields=["calendar_type", "category"],
                name="meeting_cal_calenda_7c21bd_idx",
            ),
        ),
    ]
