# Generated by Django 6.0.1 on 2026-01-25 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meeting", "0007_calendar_calendar_type_calendar_parent_and_more"),
        ("project", "0002_timesheetentry_workdiaryentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schedules",
                to="project.project",
                verbose_name="프로젝트",
            ),
        ),
    ]
