# Generated by Django 6.0.1 on 2026-01-26 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meeting", "0008_schedule_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="project",
        ),
    ]
