# Generated by Django 6.0.1 on 2026-01-12 00:15

import django.db.models.deletion
import resources.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="폴더명")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="공개 여부"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_folders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="소유자",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subfolders",
                        to="resources.folder",
                        verbose_name="상위 폴더",
                    ),
                ),
            ],
            options={
                "verbose_name": "폴더",
                "verbose_name_plural": "폴더",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="파일명")),
                (
                    "file",
                    models.FileField(
                        upload_to=resources.models.resource_upload_path,
                        verbose_name="파일",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("file", "파일"),
                            ("image", "이미지"),
                            ("document", "문서"),
                            ("video", "동영상"),
                            ("archive", "압축파일"),
                            ("other", "기타"),
                        ],
                        default="file",
                        max_length=20,
                        verbose_name="파일 유형",
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(default=0, verbose_name="파일 크기"),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="MIME 타입"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="쉼표로 구분",
                        max_length=200,
                        verbose_name="태그",
                    ),
                ),
                (
                    "download_count",
                    models.PositiveIntegerField(default=0, verbose_name="다운로드 수"),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="조회 수"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="resources.folder",
                        verbose_name="폴더",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_resources",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="업로더",
                    ),
                ),
            ],
            options={
                "verbose_name": "자료",
                "verbose_name_plural": "자료",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DownloadHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "downloaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="다운로드 시간"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP 주소"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="download_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="download_history",
                        to="resources.resource",
                        verbose_name="자료",
                    ),
                ),
            ],
            options={
                "verbose_name": "다운로드 이력",
                "verbose_name_plural": "다운로드 이력",
                "ordering": ["-downloaded_at"],
            },
        ),
    ]
