# Generated by Django 6.0.1 on 2026-01-16 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="downloadhistory",
            name="user_agent",
            field=models.TextField(blank=True, verbose_name="User Agent"),
        ),
        migrations.AddField(
            model_name="folder",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="삭제일"),
        ),
        migrations.AddField(
            model_name="folder",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_folders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="삭제자",
            ),
        ),
        migrations.AddField(
            model_name="folder",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="삭제됨"),
        ),
        migrations.AddField(
            model_name="folder",
            name="owner_scope",
            field=models.CharField(
                choices=[
                    ("personal", "개인"),
                    ("team", "팀"),
                    ("department", "부서"),
                    ("company", "전사"),
                ],
                default="personal",
                max_length=20,
                verbose_name="소유 범위",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="checksum",
            field=models.CharField(
                blank=True,
                help_text="SHA256 해시",
                max_length=64,
                verbose_name="체크섬",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="삭제일"),
        ),
        migrations.AddField(
            model_name="resource",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_resources",
                to=settings.AUTH_USER_MODEL,
                verbose_name="삭제자",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="만료일"),
        ),
        migrations.AddField(
            model_name="resource",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="삭제됨"),
        ),
        migrations.AddField(
            model_name="resource",
            name="is_temporary",
            field=models.BooleanField(default=False, verbose_name="임시파일"),
        ),
        migrations.AddField(
            model_name="resource",
            name="original_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="원본 파일명"
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="previous_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="newer_versions",
                to="resources.resource",
                verbose_name="이전 버전",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="version",
            field=models.PositiveIntegerField(default=1, verbose_name="버전"),
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("upload", "업로드"),
                            ("download", "다운로드"),
                            ("preview", "미리보기"),
                            ("move", "이동"),
                            ("rename", "이름변경"),
                            ("delete", "삭제"),
                            ("restore", "복원"),
                            ("purge", "영구삭제"),
                            ("create_folder", "폴더생성"),
                        ],
                        max_length=20,
                        verbose_name="액션",
                    ),
                ),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="상세정보"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP 주소"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to="resources.folder",
                        verbose_name="폴더",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to="resources.resource",
                        verbose_name="자료",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_activity_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "활동 로그",
                "verbose_name_plural": "활동 로그",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AttachmentLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("contact", "업무연락"),
                            ("board", "게시판"),
                            ("approval", "전자결재"),
                            ("chat", "메신저"),
                            ("meeting", "회의"),
                        ],
                        max_length=20,
                        verbose_name="출처 유형",
                    ),
                ),
                ("source_id", models.PositiveIntegerField(verbose_name="출처 ID")),
                (
                    "source_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="출처 제목"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachment_links",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachment_links",
                        to="resources.resource",
                        verbose_name="문서",
                    ),
                ),
            ],
            options={
                "verbose_name": "첨부파일 연결",
                "verbose_name_plural": "첨부파일 연결",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["source_type", "source_id"],
                        name="resources_a_source__b039e1_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FolderPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.CharField(blank=True, max_length=100, verbose_name="부서"),
                ),
                (
                    "permission",
                    models.CharField(
                        choices=[
                            ("read", "읽기"),
                            ("write", "쓰기"),
                            ("delete", "삭제"),
                            ("admin", "관리"),
                        ],
                        max_length=20,
                        verbose_name="권한",
                    ),
                ),
                (
                    "inherit",
                    models.BooleanField(
                        default=True,
                        help_text="하위 폴더에 권한 상속",
                        verbose_name="상속",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="resources.folder",
                        verbose_name="폴더",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folder_permissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "폴더 권한",
                "verbose_name_plural": "폴더 권한",
                "unique_together": {("folder", "user", "permission")},
            },
        ),
    ]
