# Generated by Django 6.0.1 on 2026-01-13 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimelineEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("approval", "결재"),
                            ("board", "게시판"),
                            ("schedule", "일정"),
                            ("task", "업무"),
                            ("announcement", "공지"),
                            ("attendance", "근태/출결"),
                            ("survey", "설문조사"),
                        ],
                        default="board",
                        max_length=20,
                        verbose_name="활동 유형",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("content", models.TextField(blank=True, verbose_name="내용")),
                (
                    "reference_model",
                    models.CharField(
                        blank=True,
                        help_text="예: approval.Document, board.Post",
                        max_length=50,
                        verbose_name="참조 모델",
                    ),
                ),
                (
                    "reference_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="참조 ID"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "타임라인 이벤트",
                "verbose_name_plural": "타임라인 이벤트",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TimelineFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="timeline.timelineevent",
                        verbose_name="이벤트",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_favorites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "즐겨찾기",
                "verbose_name_plural": "즐겨찾기",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="timelineevent",
            index=models.Index(
                fields=["-created_at"], name="timeline_ti_created_575111_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timelineevent",
            index=models.Index(
                fields=["activity_type", "-created_at"],
                name="timeline_ti_activit_eb14be_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="timelineevent",
            index=models.Index(
                fields=["author", "-created_at"], name="timeline_ti_author__36dd01_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="timelinefavorite",
            unique_together={("user", "event")},
        ),
    ]
