# Generated by Django 6.0.1 on 2026-02-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tree",
                    models.JSONField(blank=True, null=True, verbose_name="조직도"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizations",
                        to="core.company",
                        verbose_name="회사",
                    ),
                ),
            ],
            options={
                "verbose_name": "조직도",
                "verbose_name_plural": "조직도",
            },
        ),
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.UniqueConstraint(
                fields=("company",), name="uniq_company_organization"
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["company"], name="org_company_idx"),
        ),
    ]
