# Generated by Django 6.0.1 on 2026-02-23

from django.db import migrations, models


def populate_department_order(apps, schema_editor):
    Department = apps.get_model("core", "Department")

    company_ids = (
        Department.objects.order_by()
        .values_list("company_id", flat=True)
        .distinct()
    )

    for company_id in company_ids:
        departments = (
            Department.objects.filter(company_id=company_id)
            .order_by("name", "id")
        )
        for index, department in enumerate(departments, start=1):
            Department.objects.filter(pk=department.pk).update(order=index)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="정렬 순서"),
        ),
        migrations.RunPython(populate_department_order, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name="department",
            options={
                "ordering": ["company_id", "order", "name"],
                "verbose_name": "부서",
                "verbose_name_plural": "부서 목록",
            },
        ),
    ]
